export const SERVICES = [
  {
    id: 'argocd',
    name: 'ArgoCD',
    description: 'GitOps continuous delivery for Kubernetes',
    domain: 'Terminus',
    service: 'Platform',
    category: 'infra',
    url: 'https://argocd.trantor.internal/',
    iconSlug: 'argocd',
    healthCheck: { url: 'https://argocd.trantor.internal/healthz', enabled: true },
    enabled: true,
  },
  {
    id: 'vault',
    name: 'Vault',
    description: 'Secrets management and PKI',
    domain: 'Terminus',
    service: 'Platform',
    category: 'infra',
    url: 'https://vault.trantor.internal:8200/ui/vault/auth',
    iconSlug: 'vault',
    healthCheck: { url: 'https://vault.trantor.internal:8200/v1/sys/health', enabled: true },
    enabled: true,
  },
  {
    id: 'semaphore',
    name: 'Semaphore',
    description: 'Ansible automation UI',
    domain: 'Terminus',
    service: 'Platform',
    category: 'infra',
    url: 'https://semaphore.trantor.internal',
    iconSlug: 'semaphoreui',
    healthCheck: { url: 'https://semaphore.trantor.internal/api/ping', enabled: true },
    enabled: true,
  },
  {
    id: 'proxmox',
    name: 'Proxmox',
    description: 'Hypervisor and VM management',
    domain: 'Terminus',
    service: 'Platform',
    category: 'infra',
    url: 'https://10.0.0.48:8006',
    iconSlug: 'proxmox',
    healthCheck: {
      url: 'https://10.0.0.48:8006/api2/json/version',
      enabled: true,
    },
    enabled: true,
  },
  {
    id: 'ollama',
    name: 'Ollama Gateway',
    description: 'Local LLM inference gateway',
    domain: 'Terminus',
    service: 'AI',
    category: 'ai',
    url: 'https://ollama.trantor.internal',
    iconSlug: 'ollama',
    healthCheck: { url: 'https://ollama.trantor.internal/api/version', enabled: true },
    enabled: true,
  },
  {
    id: 'grafana',
    name: 'Grafana',
    description: 'Metrics and observability dashboards',
    domain: 'Terminus',
    service: 'Platform',
    category: 'monitoring',
    url: 'https://grafana.trantor.internal',
    iconSlug: 'grafana',
    healthCheck: { url: 'https://grafana.trantor.internal/api/health', enabled: true },
    enabled: true,
  },
  {
    id: 'fourdogs',
    name: 'Fourdogs',
    description: 'Pet supply operations — orders, suggestions, inventory',
    domain: 'Fourdogs',
    service: 'Central',
    category: 'app',
    url: 'https://fourdogs-central.trantor.internal',
    iconSlug: '',
    healthCheck: { url: 'https://fourdogs-central.trantor.internal/v1/health', enabled: true },
    enabled: true,
  },
  {
    id: 'kaylee-agent',
    name: 'Kaylee Agent',
    description: 'AI agent service for order coaching and suggestions',
    domain: 'Terminus',
    service: 'AI',
    category: 'ai',
    url: 'https://kaylee-agent.trantor.internal',
    iconSlug: '',
    healthCheck: { url: 'https://kaylee-agent.trantor.internal/health/live', enabled: true },
    enabled: true,
  },
];
