export const SERVICES = [
  {
    id: 'argocd',
    name: 'ArgoCD',
    description: 'GitOps continuous delivery for Kubernetes',
    category: 'infra',
    url: 'https://argocd.trantor.internal/',
    iconSlug: 'argocd',
    healthCheck: { url: 'https://argocd.trantor.internal/healthz', enabled: true },
    enabled: true,
  },
  {
    id: 'vault',
    name: 'Vault',
    description: 'Secrets management and PKI',
    category: 'infra',
    url: 'https://vault.trantor.internal:8200/ui/vault/auth',
    iconSlug: 'vault',
    healthCheck: { url: 'https://vault.trantor.internal:8200/v1/sys/health', enabled: true },
    enabled: true,
  },
  {
    id: 'semaphore',
    name: 'Semaphore',
    description: 'Ansible automation UI',
    category: 'infra',
    url: 'https://semaphore.trantor.internal',
    iconSlug: 'semaphoreui',
    healthCheck: { url: 'https://semaphore.trantor.internal/api/ping', enabled: true },
    enabled: true,
  },
  {
    id: 'proxmox',
    name: 'Proxmox',
    description: 'Hypervisor and VM management',
    category: 'infra',
    url: 'https://proxmox.trantor.internal:8006',
    iconSlug: 'proxmox',
    healthCheck: {
      url: 'https://proxmox.trantor.internal:8006/api2/json/version',
      enabled: true,
    },
    enabled: true,
  },
  {
    id: 'consul',
    name: 'Consul',
    description: 'Service discovery and mesh',
    category: 'infra',
    url: 'http://vault.trantor.internal:8500/ui',
    iconSlug: 'consul',
    healthCheck: { url: 'http://vault.trantor.internal:8500/v1/status/leader', enabled: true },
    enabled: true,
  },
  {
    id: 'pgadmin',
    name: 'pgAdmin',
    description: 'PostgreSQL administration',
    category: 'data',
    url: 'https://pgadmin.trantor.internal',
    iconSlug: 'postgresql',
    healthCheck: { url: 'https://pgadmin.trantor.internal/misc/ping', enabled: true },
    enabled: true,
  },
  {
    id: 'ollama',
    name: 'Ollama Gateway',
    description: 'Local LLM inference gateway',
    category: 'ai',
    url: 'https://ollama.trantor.internal',
    iconSlug: 'ollama',
    healthCheck: { url: 'https://ollama.trantor.internal/api/version', enabled: true },
    enabled: true,
  },
  {
    id: 'grafana',
    name: 'Grafana',
    description: 'Metrics and observability dashboards',
    category: 'monitoring',
    url: 'https://grafana.trantor.internal',
    iconSlug: 'grafana',
    healthCheck: { url: 'https://grafana.trantor.internal/api/health', enabled: true },
    enabled: true,
  },
  {
    id: 'fourdogs',
    name: 'Fourdogs',
    description: 'Pet supply operations — orders, suggestions, inventory',
    category: 'app',
    url: 'https://fourdogs-central.trantor.internal',
    iconSlug: '',
    healthCheck: { url: 'https://fourdogs-central.trantor.internal/v1/health', enabled: true },
    enabled: true,
  },
  {
    id: 'kaylee-agent',
    name: 'Kaylee Agent',
    description: 'AI agent service for order coaching and suggestions',
    category: 'app',
    url: 'https://kaylee-agent.trantor.internal',
    iconSlug: '',
    healthCheck: { url: 'https://kaylee-agent.trantor.internal/health/live', enabled: true },
    enabled: true,
  },
];
